### PR TITLE
Create contributing.md and updating README file

### PR DESCRIPTION
**Pull request by utkarsh006**
Issue #13 and #11 
- This PR solves both issues so that the time is not wasted in documentation and more features can be build for the project.
- This PR updates README and adds contributing as well as installation guidelines.
- See changes [here](https://github.com/utkarsh006/CrazyCoderApp/tree/utk-contribute)

### CODE REVIEW

**Comment by utkarsh006** [comment]
Don't merge the PR. Work in progress.

**Comment by utkarsh006** [comment]
@Yash-Parsana Issue is solved. Kindly Review.

**Comment by Yash-Parsana** [comment]
You were assigned issue #13 , so make PR just for issue #13 other contributor working on issue #11.

**Comment by utkarsh006** [comment]
@Yash-Parsana I think you didn't get my intention. The man who created 2 issues was for the purpose of getting more points in the program. However, if we see clearly there is no much documentation involved in the process to create 2 separate issues. Hope you understand this and will act positively.

**Comment by Yash-Parsana** [comment]
Issue #11 already assigned and i want detailed ReadMe file so keep it seprate.
Thank You.

**Comment by utkarsh006** [comment]
@Yash-Parsana Harsh is simultaneously working on two issues which violates the spirit of the program. Moreover, detailed README file can adds up more information and make it lengthy hence stopping users to read all of it. Hence, I have created modularity in this PR.

**Comment by utkarsh006** [comment]
@Yash-Parsana Just see the files changed. It's only 2 in number which is minimum and if you still have issues in merging this PR or about the features we can move on this problem to the program manager.

**Pull request closed without merging**
