### PR TITLE
Marketing Website for the App

### LINKED ISSUE #84: Full Stack Website for the crazy code app
### Is your feature request related to a problem? Please describe.

The app currently does not have a marketing or web-app type website.

### Describe the solution you'd like

To create such a website or a Web-APP powered by the same express backend.

### Describe alternatives you've considered

Using React, and beautiful animations for the site.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kushagra102**
## Related Issue
Fixes #84 

## Description
Built a basic starter website for the web-app. 

## Screenshots
image

image

image

image

image

## Checklist 

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [ ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Kushagra102** [comment]
@Yash-Parsana Please review this PR.

**Review by Pranshu1902 — APPROVED** [review]

**Comment by Pranshu1902** [comment]
LGTM @Yash-Parsana

**Comment by Yash-Parsana** [comment]
Have you Hosted it ?

**Comment by Yash-Parsana** [comment]
@Pranshu1902 
Please Host it on vercel.
I think it don't required backend.

**Comment by Yash-Parsana** [comment]
And Please make sure all the links working fine in website including social link in last page bottom right.

**Comment by Pranshu1902** [comment]
@Kushagra102 please deploy the site on Vercel and send the link. @Yash-Parsana you accidentally assigned this PR to me instead of @Kushagra102. Please correct that.

**Comment by Kushagra102** [comment]
@Yash-Parsana @Pranshu1902 Okay I will share the link after deploying.

**Comment by Yash-Parsana** [comment]
@Kushagra102 
Please make it fast, try to finish it by tomorrow.

**Comment by Kushagra102** [comment]
@Yash-Parsana I will deploy it today and give the link 👍🏼

**Comment by Kushagra102** [comment]
https://website2-livid.vercel.app/ 
@Yash-Parsana @Pranshu1902 This is the deployment link

**Comment by Yash-Parsana** [comment]
Hello @Kushagra102 you have done great job but some changes are required...

set CrazyCoder favicon and change title to CrazyCoder.
Screenshot (482)

CrazyCoder log :
CrazyCoder

Add real reviews from PlayStore:
Screenshot (483)

add linkedIn handle and attach this https://www.linkedin.com/in/yash-parsana-a9176a1b2/ link and also attach github repo link with github icon.

Screenshot (484)


Deploy this changes.

Do it as soon as possible so that i can merge it.

Thank You

**Comment by Kushagra102** [comment]
@Yash-Parsana will do the necessary changes .

**Comment by Kushagra102** [comment]
@Yash-Parsana  Been busy with the final exams will create the request as soon as possible.

**Comment by Kushagra102** [comment]
@Yash-Parsana Will finish it by tonight.

**Comment by Kushagra102** [comment]
image
image
image

Required changes done.

**Comment by Kushagra102** [comment]
@Yash-Parsana  Please Review this pr.
https://website2-livid.vercel.app/

**Pull request merged**
