### PR TITLE
Land scape mode added successfully.

### PR DESCRIPTION
**Pull request by Namanbansal06**
Send me your email or discord channel so that i can share you the detailed video.

### CODE REVIEW

**Comment by Yash-Parsana** [comment]
You ahve to share it here.
just drag and drop video in comment box it will be uploaded.

**Comment by Yash-Parsana** [comment]
Your PR containing unnecessary changes You just have to change whatever you called.

**Comment by Namanbansal06** [comment]
Video size is getting out of limit... It is unable to load a 30 sec video..
That's why I was unable to share the video here... 

Here are some snaps of my work.

**Comment by Namanbansal06** [comment]
> Your PR containing unnecessary changes You just have to change whatever you called.

Sir i made few changes which were necessary.
These are the changes I made :-
1 change in Mainfest file of orientation mode into unspecified
2 change in leaderboard fragment , connecting the leaderboard frag with an activity to avoid app crash
3 added scroll view in signup page and in chats fragment plus button
4 change in Mainfest file main activity to resume activity on state change.
These are the changes I made.

I can breify explain you in detail if you want.

**Comment by Namanbansal06** [comment]
Sir tell me any update what change I need to do or everything fine.

**Comment by Pranshu1902** [comment]
@Namanbansal06 refrain from uploading so many screenshots, instead record the video using some platform like loom and share the video link next time.

**Comment by Pranshu1902** [comment]
LGTM @Yash-Parsana

**Comment by Namanbansal06** [comment]
https://drive.google.com/file/d/1U1kRvbHQ250fHE-uTQL55BLazBY6OAqD/view?usp=drivesdk

Video link

**Comment by Pranshu1902** [comment]
> https://drive.google.com/file/d/1U1kRvbHQ250fHE-uTQL55BLazBY6OAqD/view?usp=drivesdk
> 
> Video link

LGTM @Yash-Parsana

**Review by Pranshu1902 — APPROVED** [review]

**Pull request closed without merging**
