### PR TITLE
Adding vectors to the SignUp page 

### PR DESCRIPTION
**Pull request by NehaVns**
I have successfully added the vectors and tested the application.

### CODE REVIEW

**Comment by Pranshu1902** [comment]
@NehaVns please resolve the merge conflicts

**Comment by NehaVns** [comment]
I have resolved the conflicts from my side. Kindly confirm.

**Comment by NehaVns** [comment]
✅ Issue Resolved @Yash-Parsana

**Comment by Yash-Parsana** [comment]
@NehaVns 
Please can you share screenshot of your work such that i can suggest if any changes required.

**Pull request closed without merging**
